; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#include "gimucomm.iss"
[Setup]
OutputBaseFilename=gimufree_setup_32
ArchitecturesAllowed=x86 x64
SourceDir=..\..\exe\i386\release

[Files]
Source: "..\..\..\deps\vcruntime\VC_x86Runtime.exe"; DestDir: "{app}";Flags: ignoreversion deleteafterinstall;DestName: "runtime.exe"



