; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!


[Setup]
OutputBaseFilename=gimu_setup_32_enterprise
ArchitecturesAllowed=x86 x64
SourceDir=..\..\exe\i386\release_enterprise

[Files]
Source: "..\..\..\deps\vcruntime\VC_x86Runtime.exe"; DestDir: "{app}";Flags: ignoreversion deleteafterinstall;DestName: "runtime.exe"

#include "gimucomm.iss"


