; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!


[Setup]
OutputBaseFilename=gimu_setup_x64_enterprise
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
SourceDir=..\..\exe\x64\release_enterprise

[Files]
Source: "..\..\..\deps\vcruntime\VC_x64Runtime.exe"; DestDir: "{app}";Flags: ignoreversion deleteafterinstall;DestName: "runtime.exe"

#include "gimucomm.iss"